---
functional:
  - "Пользователь может создать игру, выбрав язык программирования"
  - "Пользователь может присоединиться к уже созданной открытой игре"
  - "Пользователь может пригласить другого игрока по ссылке"
  - "Во время игры отображается код соперника в реальном времени"
  - |
    Пользователь видит результаты запуска тестов своей
    и чужой программы
  - "В процессе игры доступен чат для общения с соперником и зрителями"
  - "Пользователь может наблюдать за игрой в роли зрителя"
  - "Пользователь может использовать расширение для Chrome для отслеживания игр"

non-functional:
  - "Поддерживаются языки программирования: JavaScript, PHP, Python, Ruby"
  - "Интерфейс фронтенда реализован как одностраничное приложение (SPA)"
  - "Бэкенд реализован на Elixir с использованием фреймворка Phoenix"
  - "Тесты к задачам автоматически преобразуются на все поддерживаемые языки"
  - "Приложение разворачивается в контейнерах Docker"

implicit:
  - "Игра доступна для пользователей с разным уровнем подготовки"
  - "Интерфейс понятен без изучения документации"
  - "Система обрабатывает ошибки без сбоев"
  - "Все участники видят актуальное состояние в реальном времени"
  - "Расширение Chrome соответствует требованиям магазина"
